### ISSUE TITLE
clipart_comb.txt

### ISSUE THREAD

**Issue by HIHIHAHEI** [liyunsheng13/DRT#3]
Hi, 
I'm trying to train the model by using clipart, and there are some problems in process:
![image](https://user-images.githubusercontent.com/40845081/119211012-59637e80-bae2-11eb-9a60-ff1937dfd9c8.png)

**Comment by HIHIHAHEI** [comment]
Can you share your processed dataset?
Thanks！

**Comment by liyunsheng13** [comment]
Hi, thanks for your interest in my work. I'm not sure what exactly your problem is. It seems to me you need to first download the DomainNet dataset into your local disk and then read the images.

**Comment by HIHIHAHEI** [comment]
Yes! Thanks for your reply. Well, actually, I've downloaded the dataset, and there is a new problem, let me show you:
![image](https://user-images.githubusercontent.com/40845081/119243333-44e1bd80-bb98-11eb-915e-4454213d5ed6.png)
This is my command:
![image](https://user-images.githubusercontent.com/40845081/119243344-54f99d00-bb98-11eb-80e4-c96839db539c.png)

And the problem is:
![image](https://user-images.githubusercontent.com/40845081/119243349-6347b900-bb98-11eb-95dc-de8a3ceea6ea.png)

The painting dataset is composed as follow:
![image](https://user-images.githubusercontent.com/40845081/119243366-85d9d200-bb98-11eb-91a6-8b99df2dcbb2.png)

So, is there some problem, please help me?

**Comment by liyunsheng13** [comment]
I think it is because the official dataset was changed. You can download their txt files and merge them together with 'cat' in linux.

**Comment by liyunsheng13** [comment]
Another reason is you used the cleaned version, which is a little different compared to the version I use. You can download the original version under the cleaned version on the official website. Then you should be fine. I have tested that the model performs very similar to the two versions.

**Comment by HIHIHAHEI** [comment]
Thank you!

**Comment by HIHIHAHEI** [comment]
By the way, can you tell me how you get the comb.txt like clipart_comb.txt

**Comment by liyunsheng13** [comment]
You can use the command 'cat' on linux system.

**Comment by HIHIHAHEI** [comment]
Thank you very much!
