### ISSUE TITLE
how to train on different domains？

### ISSUE THREAD

**Issue by ccwang-nwpu** [liyunsheng13/DRT#6]
Hi Yunsheng Li, thanks a lot for sharing this implementation.

this is the first time I've run domain adapation code, I want to know to train the model on different domains?
for example, I use the pretrained model "resnet_dy_pretrained.pth" to train on clipart data, and obtain new model "model_best.pth.tar". then I use "model_best.pth.tar" as the pretrained model to train infograph data?

**Comment by ccwang-nwpu** [comment]
or just combine the clipart_comb.txt and infograph_comb.txt together? and train on the "resnet_dy_pretrained.pth"?

**Comment by liyunsheng13** [comment]
I'm not sure what your target is. If you want to work on multi-source domain adaptation task, you just need to follow the instruction in the readme file and change the training script under the folder 'script' for different datasets. If you are interested in single source domain adaptation problem, you can just change the variable -src-path to the source dataset you want to use.

**Comment by ccwang-nwpu** [comment]
My previous description was not very clear.
In your clipart_train.sh file, "--src_path clipart_comb. TXT --trg_path clipart_train. TXT --val_path clipart_test.txt."
1. Clipart_comb. TXT is a combination of clipart_train. TXT and clipart_test. TXT?
2. if i run the code as the instruction in the clipart_train.sh file,  then i can obtain a model trained on a single source domain?

if there are **2** source domains: Clipart and Infograph, and **1** target domain: Painting, then what are  the "--src_path, --trg_path, --val_path"?
--src_path is the combination of clipart_train. txt, clipart_test, txt, Infograph_train, txt, Infograph_test. txt,  painting_train. txt, painting_test. txt? Or is the combination of clipart_train. txt, Infograph_train. txt,  painting_train. txt?
-- trg_path is painting_train. txt?
-- val_path is painting_test. txt?

THANKS a lot for your reply!

**Comment by liyunsheng13** [comment]
The clipart_comb.txt is a combination of the datasets except for 'clipart'. The instruction is used to train a model with multiple source domains. If there are 2 source domains, you can build the source domain file by using 'cat' in linux to combine clipart_train.txt and infograph_train.txt and the trg_path/val_path should be painting_train.txt/painting_test.txt respectively.

**Comment by ccwang-nwpu** [comment]
THANKS a lot for your reply!
